# Generated by Django 6.0 on 2026-01-22 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imię', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=60)),
                ('url', models.URLField(max_length=180)),
                ('notatki', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Osoba',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imię', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=60)),
                ('telefon', models.CharField(max_length=20)),
                ('notatki', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Książka',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tytuł', models.CharField(max_length=60)),
                ('isbn', models.CharField(max_length=30)),
                ('jakość', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True)),
                ('stan', models.IntegerField(choices=[('chciana', 'chciana'), ('do przeczytania', 'do przeczytania'), ('czytana', 'czytana'), ('przeczytana', 'przeczytana')])),
                ('notatki', models.TextField(null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='książki.autor')),
                ('właściciel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='książki.osoba')),
            ],
        ),
    ]
