# Generated by Django 6.0 on 2026-01-27 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('książki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wypozyczenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wypozyczenia', models.DateField(auto_now_add=True)),
                ('data_zwrotu', models.DateField(blank=True, null=True)),
                ('notatki', models.TextField(blank=True, null=True)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='książki.książka')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='książki.osoba')),
            ],
        ),
    ]
