# Generated by Django 6.0 on 2026-02-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('książki', '0002_wypozyczenie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['nazwisko'], 'verbose_name_plural': 'Autors'},
        ),
        migrations.AlterModelOptions(
            name='książka',
            options={'ordering': ['tytuł'], 'verbose_name_plural': 'Ksiąki'},
        ),
        migrations.AlterModelOptions(
            name='osoba',
            options={'verbose_name_plural': 'Osoby'},
        ),
        migrations.AlterModelOptions(
            name='wypozyczenie',
            options={'ordering': ['-data_wypozyczenia']},
        ),
        migrations.AddField(
            model_name='wypozyczenie',
            name='jakość_wypozyczenia',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AddField(
            model_name='wypozyczenie',
            name='jakość_zwrotu',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True),
        ),
        migrations.AlterField(
            model_name='książka',
            name='stan',
            field=models.CharField(choices=[('chciana', 'chciana'), ('do przeczytania', 'do przeczytania'), ('czytana', 'czytana'), ('przeczytana', 'przeczytana')]),
        ),
    ]
