# Generated by Django 6.0 on 2026-02-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('książki', '0003_alter_autor_options_alter_książka_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wypozyczenie',
            new_name='Wypożyczenie',
        ),
        migrations.AlterModelOptions(
            name='książka',
            options={'ordering': ['tytuł'], 'verbose_name_plural': 'Książki'},
        ),
        migrations.AlterModelOptions(
            name='wypożyczenie',
            options={'ordering': ['-data_wypożyczenia']},
        ),
        migrations.RenameField(
            model_name='wypożyczenie',
            old_name='data_wypozyczenia',
            new_name='data_wypożyczenia',
        ),
        migrations.RenameField(
            model_name='wypożyczenie',
            old_name='jakość_wypozyczenia',
            new_name='jakość_wypożyczenia',
        ),
        migrations.RenameField(
            model_name='wypożyczenie',
            old_name='ksiazka',
            new_name='książka',
        ),
        migrations.AlterField(
            model_name='książka',
            name='stan',
            field=models.CharField(choices=[('chciana', 'chciana'), ('do przeczytania', 'do przeczytania'), ('czytana', 'czytana'), ('przeczytana', 'przeczytana')], max_length=30),
        ),
    ]
